PROPERTIES = [{'id': 'prop-001',
  'address': '1842 Maple Ridge Dr',
  'city': 'Arlington',
  'state': 'VA',
  'zip': '22201',
  'price': 875000,
  'beds': 4,
  'baths': 3,
  'sqft': 2400,
  'property_type': 'house',
  'year_built': 1998,
  'description': 'Sun-filled colonial on a quiet tree-lined street, updated kitchen with quartz '
                 'counters, finished basement, and fenced backyard.',
  'features': ['garage', 'fireplace', 'updated kitchen', 'fenced yard', 'basement'],
  'neighborhood': 'Clarendon',
  'status': 'for_sale'},
 {'id': 'prop-002',
  'address': '5201 Wilson Blvd Unit 8F',
  'city': 'Arlington',
  'state': 'VA',
  'zip': '22205',
  'price': 625000,
  'beds': 2,
  'baths': 2,
  'sqft': 1180,
  'property_type': 'condo',
  'year_built': 2015,
  'description': 'Modern condo steps from Metro with floor-to-ceiling windows, in-unit laundry, '
                 'and building gym.',
  'features': ['metro nearby', 'gym', 'in-unit laundry', 'balcony', 'doorman'],
  'neighborhood': 'Ballston',
  'status': 'for_sale'},
 {'id': 'prop-003',
  'address': '903 Oak Hill Ln',
  'city': 'Austin',
  'state': 'TX',
  'zip': '78704',
  'price': 749000,
  'beds': 3,
  'baths': 2.5,
  'sqft': 1950,
  'property_type': 'house',
  'year_built': 2005,
  'description': 'South Austin charmer with open floor plan, covered patio, and walkable access to '
                 'coffee shops and trails.',
  'features': ['patio', 'open floor plan', 'hardwood floors', 'two-car garage'],
  'neighborhood': 'Zilker',
  'status': 'for_sale'},
 {'id': 'prop-004',
  'address': '2210 Barton Springs Rd',
  'city': 'Austin',
  'state': 'TX',
  'zip': '78746',
  'price': 1195000,
  'beds': 4,
  'baths': 3.5,
  'sqft': 3100,
  'property_type': 'house',
  'year_built': 2018,
  'description': "Architect-designed home with pool, chef's kitchen, and primary suite overlooking "
                 'mature oaks.',
  'features': ['pool', 'chef kitchen', 'primary suite', 'smart home', 'three-car garage'],
  'neighborhood': 'Barton Hills',
  'status': 'for_sale'},
 {'id': 'prop-005',
  'address': '88 Beacon St Unit 12A',
  'city': 'Boston',
  'state': 'MA',
  'zip': '02108',
  'price': 985000,
  'beds': 2,
  'baths': 2,
  'sqft': 1050,
  'property_type': 'condo',
  'year_built': 1920,
  'description': 'Historic Beacon Hill condo with exposed brick, bay windows, and Charles River '
                 'views.',
  'features': ['river views', 'exposed brick', 'historic building', 'concierge'],
  'neighborhood': 'Beacon Hill',
  'status': 'for_sale'},
 {'id': 'prop-006',
  'address': '4120 Lakeview Terrace',
  'city': 'Denver',
  'state': 'CO',
  'zip': '80211',
  'price': 689000,
  'beds': 3,
  'baths': 2,
  'sqft': 1780,
  'property_type': 'house',
  'year_built': 1945,
  'description': 'Renovated bungalow with mountain views, landscaped garden, and detached studio.',
  'features': ['mountain views', 'studio', 'garden', 'updated HVAC'],
  'neighborhood': "Sloan's Lake",
  'status': 'for_sale'},
 {'id': 'prop-007',
  'address': '1550 Pearl St Unit 304',
  'city': 'Denver',
  'state': 'CO',
  'zip': '80203',
  'price': 525000,
  'beds': 1,
  'baths': 1,
  'sqft': 780,
  'property_type': 'condo',
  'year_built': 2019,
  'description': 'Boutique loft-style condo near shops and dining with rooftop deck access.',
  'features': ['rooftop deck', 'loft layout', 'bike storage', 'pet friendly'],
  'neighborhood': 'Capitol Hill',
  'status': 'for_sale'},
 {'id': 'prop-008',
  'address': '774 Mar Vista Ave',
  'city': 'Los Angeles',
  'state': 'CA',
  'zip': '90036',
  'price': 1349000,
  'beds': 3,
  'baths': 2,
  'sqft': 1650,
  'property_type': 'house',
  'year_built': 1936,
  'description': 'Spanish revival with original details, drought-tolerant landscaping, and '
                 'detached garage.',
  'features': ['spanish revival', 'original details', 'garage', 'landscaped yard'],
  'neighborhood': 'Mid-Wilshire',
  'status': 'for_sale'},
 {'id': 'prop-009',
  'address': '3300 Riverside Dr',
  'city': 'Los Angeles',
  'state': 'CA',
  'zip': '90027',
  'price': 2195000,
  'beds': 4,
  'baths': 3.5,
  'sqft': 2800,
  'property_type': 'house',
  'year_built': 2012,
  'description': 'Hillside contemporary with canyon views, infinity pool, and indoor-outdoor '
                 'living.',
  'features': ['pool', 'canyon views', 'home office', 'wine cellar'],
  'neighborhood': 'Los Feliz',
  'status': 'for_sale'},
 {'id': 'prop-010',
  'address': '19 Harbor View Ct',
  'city': 'Seattle',
  'state': 'WA',
  'zip': '98119',
  'price': 1125000,
  'beds': 3,
  'baths': 2.5,
  'sqft': 2100,
  'property_type': 'townhouse',
  'year_built': 2016,
  'description': 'Water-view townhouse with rooftop terrace, EV charging, and designer finishes.',
  'features': ['water views', 'rooftop terrace', 'EV charging', 'designer finishes'],
  'neighborhood': 'Queen Anne',
  'status': 'for_sale'},
 {'id': 'prop-011',
  'address': '4401 Greenlake Way N',
  'city': 'Seattle',
  'state': 'WA',
  'zip': '98103',
  'price': 945000,
  'beds': 4,
  'baths': 3,
  'sqft': 2300,
  'property_type': 'house',
  'year_built': 2001,
  'description': 'Family home near the lake trail with sunroom, mudroom, and large deck.',
  'features': ['deck', 'sunroom', 'mudroom', 'near lake trail'],
  'neighborhood': 'Green Lake',
  'status': 'for_sale'},
 {'id': 'prop-012',
  'address': '210 Peachtree Hills Cir NE',
  'city': 'Atlanta',
  'state': 'GA',
  'zip': '30305',
  'price': 795000,
  'beds': 4,
  'baths': 3,
  'sqft': 2550,
  'property_type': 'house',
  'year_built': 1992,
  'description': 'Classic Buckhead-area home with formal dining, screened porch, and level '
                 'backyard.',
  'features': ['screened porch', 'formal dining', 'level yard', 'two-car garage'],
  'neighborhood': 'Peachtree Hills',
  'status': 'for_sale'}]

NEIGHBORHOODS = [{'id': 'hood-001',
  'name': 'Clarendon',
  'city': 'Arlington',
  'state': 'VA',
  'summary': 'Walkable urban village with restaurants, Metro access, and a mix of condos and '
             'single-family homes.',
  'median_price': 720000,
  'highlights': ['Metro Orange/Silver Line', 'vibrant dining scene', 'parks and trails']},
 {'id': 'hood-002',
  'name': 'Zilker',
  'city': 'Austin',
  'state': 'TX',
  'summary': 'Laid-back South Austin neighborhood famous for Barton Springs, festivals, and '
             'outdoor lifestyle.',
  'median_price': 890000,
  'highlights': ['Barton Springs Pool', 'ACL Festival grounds', 'hike-and-bike trails']},
 {'id': 'hood-003',
  'name': 'Beacon Hill',
  'city': 'Boston',
  'state': 'MA',
  'summary': 'Historic cobblestone streets, gas lamps, and classic Boston charm near the Common '
             'and river.',
  'median_price': 1150000,
  'highlights': ['historic architecture', 'Charles River Esplanade', 'excellent transit']},
 {'id': 'hood-004',
  'name': 'Los Feliz',
  'city': 'Los Angeles',
  'state': 'CA',
  'summary': 'Hillside neighborhood with creative energy, Griffith Park access, and eclectic '
             'dining.',
  'median_price': 1850000,
  'highlights': ['Griffith Observatory nearby', 'village shops', 'architectural homes']},
 {'id': 'hood-005',
  'name': 'Green Lake',
  'city': 'Seattle',
  'state': 'WA',
  'summary': 'Family-friendly area centered on a popular lake loop with strong schools and local '
             'shops.',
  'median_price': 980000,
  'highlights': ['3-mile lake loop', 'strong schools', 'community feel']}]
