PROPERTIES = [
    {
        "id": "prop-001",
        "address": "1842 Maple Ridge Dr",
        "city": "Arlington",
        "state": "VA",
        "zip": "22201",
        "price": 875000,
        "beds": 4,
        "baths": 3,
        "sqft": 2400,
        "property_type": "house",
        "year_built": 1998,
        "description": "Sun-filled colonial on a quiet tree-lined street, updated kitchen with quartz counters, finished basement, and fenced backyard.",
        "features": ["garage", "fireplace", "updated kitchen", "fenced yard", "basement"],
        "neighborhood": "Clarendon",
        "school_rating": 8,
        "walk_score": 82,
        "commute_downtown": "12 min to DC",
        "image_url": "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
        "status": "for_sale",
    },
    {
        "id": "prop-002",
        "address": "5201 Wilson Blvd Unit 8F",
        "city": "Arlington",
        "state": "VA",
        "zip": "22205",
        "price": 625000,
        "beds": 2,
        "baths": 2,
        "sqft": 1180,
        "property_type": "condo",
        "year_built": 2015,
        "description": "Modern condo steps from Metro with floor-to-ceiling windows, in-unit laundry, and building gym.",
        "features": ["metro nearby", "gym", "in-unit laundry", "balcony", "doorman"],
        "neighborhood": "Ballston",
        "school_rating": 7,
        "walk_score": 91,
        "commute_downtown": "15 min to DC",
        "image_url": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
        "status": "for_sale",
    },
    {
        "id": "prop-003",
        "address": "903 Oak Hill Ln",
        "city": "Austin",
        "state": "TX",
        "zip": "78704",
        "price": 749000,
        "beds": 3,
        "baths": 2.5,
        "sqft": 1950,
        "property_type": "house",
        "year_built": 2005,
        "description": "South Austin charmer with open floor plan, covered patio, and walkable access to coffee shops and trails.",
        "features": ["patio", "open floor plan", "hardwood floors", "two-car garage"],
        "neighborhood": "Zilker",
        "school_rating": 8,
        "walk_score": 78,
        "commute_downtown": "10 min to downtown Austin",
        "image_url": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        "status": "for_sale",
    },
    {
        "id": "prop-004",
        "address": "2210 Barton Springs Rd",
        "city": "Austin",
        "state": "TX",
        "zip": "78746",
        "price": 1195000,
        "beds": 4,
        "baths": 3.5,
        "sqft": 3100,
        "property_type": "house",
        "year_built": 2018,
        "description": "Architect-designed home with pool, chef's kitchen, and primary suite overlooking mature oaks.",
        "features": ["pool", "chef kitchen", "primary suite", "smart home", "three-car garage"],
        "neighborhood": "Barton Hills",
        "school_rating": 9,
        "walk_score": 65,
        "commute_downtown": "14 min to downtown Austin",
        "image_url": "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
        "status": "for_sale",
    },
    {
        "id": "prop-005",
        "address": "88 Beacon St Unit 12A",
        "city": "Boston",
        "state": "MA",
        "zip": "02108",
        "price": 985000,
        "beds": 2,
        "baths": 2,
        "sqft": 1050,
        "property_type": "condo",
        "year_built": 1920,
        "description": "Historic Beacon Hill condo with exposed brick, bay windows, and Charles River views.",
        "features": ["river views", "exposed brick", "historic building", "concierge"],
        "neighborhood": "Beacon Hill",
        "school_rating": 9,
        "walk_score": 97,
        "commute_downtown": "Walkable to Financial District",
        "image_url": "https://images.unsplash.com/photo-1522708323590-d24dbb4b7427?w=800&q=80",
        "status": "for_sale",
    },
    {
        "id": "prop-006",
        "address": "4120 Lakeview Terrace",
        "city": "Denver",
        "state": "CO",
        "zip": "80211",
        "price": 689000,
        "beds": 3,
        "baths": 2,
        "sqft": 1780,
        "property_type": "house",
        "year_built": 1945,
        "description": "Renovated bungalow with mountain views, landscaped garden, and detached studio.",
        "features": ["mountain views", "studio", "garden", "updated HVAC"],
        "neighborhood": "Sloan's Lake",
        "school_rating": 7,
        "walk_score": 72,
        "commute_downtown": "12 min to downtown Denver",
        "image_url": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        "status": "for_sale",
    },
    {
        "id": "prop-007",
        "address": "1550 Pearl St Unit 304",
        "city": "Denver",
        "state": "CO",
        "zip": "80203",
        "price": 525000,
        "beds": 1,
        "baths": 1,
        "sqft": 780,
        "property_type": "condo",
        "year_built": 2019,
        "description": "Boutique loft-style condo near shops and dining with rooftop deck access.",
        "features": ["rooftop deck", "loft layout", "bike storage", "pet friendly"],
        "neighborhood": "Capitol Hill",
        "school_rating": 6,
        "walk_score": 88,
        "commute_downtown": "8 min to downtown Denver",
        "image_url": "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
        "status": "for_sale",
    },
    {
        "id": "prop-008",
        "address": "774 Mar Vista Ave",
        "city": "Los Angeles",
        "state": "CA",
        "zip": "90036",
        "price": 1349000,
        "beds": 3,
        "baths": 2,
        "sqft": 1650,
        "property_type": "house",
        "year_built": 1936,
        "description": "Spanish revival with original details, drought-tolerant landscaping, and detached garage.",
        "features": ["spanish revival", "original details", "garage", "landscaped yard"],
        "neighborhood": "Mid-Wilshire",
        "school_rating": 8,
        "walk_score": 84,
        "commute_downtown": "20 min to DTLA",
        "image_url": "https://images.unsplash.com/photo-1605276374101-dee22ccb7a77?w=800&q=80",
        "status": "for_sale",
    },
    {
        "id": "prop-009",
        "address": "3300 Riverside Dr",
        "city": "Los Angeles",
        "state": "CA",
        "zip": "90027",
        "price": 2195000,
        "beds": 4,
        "baths": 3.5,
        "sqft": 2800,
        "property_type": "house",
        "year_built": 2012,
        "description": "Hillside contemporary with canyon views, infinity pool, and indoor-outdoor living.",
        "features": ["pool", "canyon views", "home office", "wine cellar"],
        "neighborhood": "Los Feliz",
        "school_rating": 9,
        "walk_score": 76,
        "commute_downtown": "18 min to DTLA",
        "image_url": "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80",
        "status": "for_sale",
    },
    {
        "id": "prop-010",
        "address": "19 Harbor View Ct",
        "city": "Seattle",
        "state": "WA",
        "zip": "98119",
        "price": 1125000,
        "beds": 3,
        "baths": 2.5,
        "sqft": 2100,
        "property_type": "townhouse",
        "year_built": 2016,
        "description": "Water-view townhouse with rooftop terrace, EV charging, and designer finishes.",
        "features": ["water views", "rooftop terrace", "EV charging", "designer finishes"],
        "neighborhood": "Queen Anne",
        "school_rating": 8,
        "walk_score": 79,
        "commute_downtown": "10 min to downtown Seattle",
        "image_url": "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
        "status": "for_sale",
    },
    {
        "id": "prop-011",
        "address": "4401 Greenlake Way N",
        "city": "Seattle",
        "state": "WA",
        "zip": "98103",
        "price": 945000,
        "beds": 4,
        "baths": 3,
        "sqft": 2300,
        "property_type": "house",
        "year_built": 2001,
        "description": "Family home near the lake trail with sunroom, mudroom, and large deck.",
        "features": ["deck", "sunroom", "mudroom", "near lake trail"],
        "neighborhood": "Green Lake",
        "school_rating": 9,
        "walk_score": 81,
        "commute_downtown": "15 min to downtown Seattle",
        "image_url": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
        "status": "for_sale",
    },
    {
        "id": "prop-012",
        "address": "210 Peachtree Hills Cir NE",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "price": 795000,
        "beds": 4,
        "baths": 3,
        "sqft": 2550,
        "property_type": "house",
        "year_built": 1992,
        "description": "Classic Buckhead-area home with formal dining, screened porch, and level backyard.",
        "features": ["screened porch", "formal dining", "level yard", "two-car garage"],
        "neighborhood": "Peachtree Hills",
        "school_rating": 8,
        "walk_score": 58,
        "commute_downtown": "18 min to downtown Atlanta",
        "image_url": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80",
        "status": "for_sale",
    },
]

NEIGHBORHOODS = [
    {
        "id": "hood-001",
        "name": "Clarendon",
        "city": "Arlington",
        "state": "VA",
        "summary": "Walkable urban village with restaurants, Metro access, and a mix of condos and single-family homes.",
        "median_price": 720000,
        "walk_score": 85,
        "school_rating": 8,
        "highlights": ["Metro Orange/Silver Line", "vibrant dining scene", "parks and trails"],
        "nearby_amenities": ["Clarendon Metro", "Whole Foods", "Quinn's Auction Galleries"],
    },
    {
        "id": "hood-002",
        "name": "Zilker",
        "city": "Austin",
        "state": "TX",
        "summary": "Laid-back South Austin neighborhood famous for Barton Springs, festivals, and outdoor lifestyle.",
        "median_price": 890000,
        "walk_score": 76,
        "school_rating": 8,
        "highlights": ["Barton Springs Pool", "ACL Festival grounds", "hike-and-bike trails"],
        "nearby_amenities": ["Zilker Park", "Barton Springs", "local coffee shops"],
    },
    {
        "id": "hood-003",
        "name": "Beacon Hill",
        "city": "Boston",
        "state": "MA",
        "summary": "Historic cobblestone streets, gas lamps, and classic Boston charm near the Common and river.",
        "median_price": 1150000,
        "walk_score": 96,
        "school_rating": 9,
        "highlights": ["historic architecture", "Charles River Esplanade", "excellent transit"],
        "nearby_amenities": ["Boston Common", "Charles River", "Mass General area"],
    },
    {
        "id": "hood-004",
        "name": "Los Feliz",
        "city": "Los Angeles",
        "state": "CA",
        "summary": "Hillside neighborhood with creative energy, Griffith Park access, and eclectic dining.",
        "median_price": 1850000,
        "walk_score": 74,
        "school_rating": 8,
        "highlights": ["Griffith Observatory nearby", "village shops", "architectural homes"],
        "nearby_amenities": ["Griffith Park", "Los Feliz Village", "Greek Theatre"],
    },
    {
        "id": "hood-005",
        "name": "Green Lake",
        "city": "Seattle",
        "state": "WA",
        "summary": "Family-friendly area centered on a popular lake loop with strong schools and local shops.",
        "median_price": 980000,
        "walk_score": 80,
        "school_rating": 9,
        "highlights": ["3-mile lake loop", "strong schools", "community feel"],
        "nearby_amenities": ["Green Lake Park", "local cafes", "community center"],
    },
]
